# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('Travel_list', models.CharField(default='', max_length=100)),
                ('is_done', models.BooleanField(default=False)),
                ('end_loc', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='end_location', to='schedule.Location_weight')),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('identifier', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=5)),
                ('Loc_per', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='travel_info',
            name='identifier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mypage.User_info'),
        ),
        migrations.AddField(
            model_name='travel_info',
            name='start_loc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='schedule.Location_weight'),
        ),
    ]
