# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_weight',
            name='loc_key',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='state_info',
            name='state_key',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='station_info',
            name='station_key',
            field=models.CharField(default='', max_length=20),
        ),
    ]
